---
title: "COVID stats"
author: "Josef Klafka"
date: "1/17/2021"
output: html_document
---

```{r setup, include=FALSE}
require(tidyverse)
require(viridis)

knitr::opts_chunk$set(echo = TRUE)
```

```{r get data, include=FALSE}

deaths <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")

cases <- read_csv("https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv?raw=true")

```

```{r dplyr data}

state_deaths <- deaths %>%
  select(Province_State, `1/16/21`) %>%
  group_by(Province_State) %>%
  summarize(deaths = sum(`1/16/21`))

state_cases <- cases %>%
  select(Province_State, `1/16/21`) %>%
  group_by(Province_State) %>%
  summarize(cases = sum(`1/16/21`))

deaths_cases <- state_deaths %>%
  left_join(state_cases, by = "Province_State") %>%
  rename(state = "Province_State") %>%
  pivot_longer(cols = c("deaths", "cases"))

```

```{r plot comparison between deaths and cases}

top_deaths_cases <- deaths_cases %>%
  group_by(state, name) %>%
  arrange(desc(value)) %>%
  ungroup() %>%
  slice(1:5) %>%
  select(state) %>%
  left_join(deaths_cases, by = "state")


top_deaths_cases %>%
  ggplot(aes(x = state)) + 
    geom_col(aes(y = value, fill = name), 
             position = position_dodge2(width = .75)) + 
    scale_fill_viridis(discrete=TRUE, begin = 0.5, direction = -1, option="inferno")

```

